### ISSUE TITLE
Apparent over folding

### ISSUE THREAD

**Issue by tartopohm** [eddiebergman/nvim-treesitter-pyfold#7]
First, thanks for the plugin!

My issue is that I cannot quite replicate the examples; it is probably linked to a bad configuration on my side rather than an actual bug, but you might be able to give some pointers.

Classes and functions at the file top level are "hidden" completely, in the sense that the whole definition line is replaced by the "> body" foldtext. It is impossible to know, at a glance, what is what without unfolding.

Illustration of what I mean:
Completely folded, I have:
![2022-10-05T09:42:00](https://user-images.githubusercontent.com/34381942/193924877-8a13a02f-8957-40c7-afde-5d0042d5d453.png)
so I do not really know what I am looking at.

After one unfolding:
![2022-10-05T09:42:26](https://user-images.githubusercontent.com/34381942/193925031-a1fd7c8d-9fc1-4d77-a470-a3966dd6747a.png)
so I do not know what the methods are.

It also happens with conditional, loops, etc.
Folded:
![2022-10-05T09:43:34](https://user-images.githubusercontent.com/34381942/193925188-f904ecf8-6404-4489-8da0-399b729604b6.png)
Unfolded:
![2022-10-05T09:43:47](https://user-images.githubusercontent.com/34381942/193925318-4031c830-7d9e-4f4f-ba7e-987e5022da5c.png)

Is this expected behaviour, or might it be caused by config conflicts?

**Comment by eddiebergman** [comment]
Hi @Tartopohm,

It seems that things aren't folding as intended, when you enter a python file, please use the following commands to debug:
```
:set foldmethod  # Should be 'expr'
:set foldexpr  # Should be "nvim_treesitter#foldexpr'
```


If this is not the case, then try setting `:set foldmethod=expr` and `:set foldexpr=nvim_treesitter#foldexpr`. If this works and you've followed the install guide completely, then something else is changing you `nvim_treesitter#foldexpr` or `foldmethod`, I would recommend doing a fuzzy find for it over your nvim config files (`.vimrc`, `ftplugin/python.vim`, ...).

If everything seems set correctly, then something is probably overwriting `nvim_treesitte#foldexpr`. You could move your treesitter config to be the last thing loaded (so that `nvim-treesitter-pyfold` is loaded after anything else that might interrupt it).

If that still doesn't work then I would need to try reproduce it and would ask for you `nvim` version and any dot files that may be relevant.

Best,
Eddie

**Comment by tartopohm** [comment]
OK, it was a conflict indeed; I am not sure how yet, but the culprit was `indent-blankline`.
It took me an embarrassingly long time of digging, thanks for pointing me to the right direction!
